### ISSUE TITLE
Can't export subsurface scattering material

### ISSUE THREAD

**Issue by Michael-Cependa** [AsoboStudio/glTF-Blender-IO-MSFS#152]
### Current Behavior

When I try to export a model which has a flight sim material set to subsurface scattering, the export fails.  If I set the object to a standard material it will export correctly. 

### Expected Behavior

I would expect the subsurface scattering material to export successfully. 

### Steps To Reproduce

Export an aircraft model containing an object with a subsurface scattering material. 

### Environment

```markdown
- OS: Windows 10
- Blender: 3.12
- glTF-Blender-IO-MSFS: 1.1.6
```

**Comment by ronh991** [comment]
ok I beleive we can reproduce your error.
Python: Traceback (most recent call last):
  File "F:\Downloads\blender-3.1.2\3.1\scripts\addons\io_scene_gltf2\__init__.py", line 651, in execute
    return gltf2_blender_export.save(context, export_settings)
  File "F:\Downloads\blender-3.1.2\3.1\scripts\addons\io_scene_gltf2\blender\exp\gltf2_blender_export.py", line 51, in save
    __write_file(json, buffer, export_settings)
  File "F:\Downloads\blender-3.1.2\3.1\scripts\addons\io_scene_gltf2\blender\exp\gltf2_blender_export.py", line 144, in __write_file
    gltf2_io_export.save_gltf(
  File "F:\Downloads\blender-3.1.2\3.1\scripts\addons\io_scene_gltf2\io\exp\gltf2_io_export.py", line 63, in save_gltf
    gltf_encoded = json.dumps(gltf_ordered, indent=indent, separators=separators, cls=encoder, allow_nan=False)
  File "F:\Downloads\blender-3.1.2\3.1\python\lib\json\__init__.py", line 238, in dumps
    **kw).encode(obj)
  File "F:\Downloads\blender-3.1.2\3.1\python\lib\json\encoder.py", line 201, in encode
    chunks = list(chunks)
  File "F:\Downloads\blender-3.1.2\3.1\python\lib\json\encoder.py", line 431, in _iterencode
    yield from _iterencode_dict(o, _current_indent_level)
  File "F:\Downloads\blender-3.1.2\3.1\python\lib\json\encoder.py", line 405, in _iterencode_dict
    yield from chunks
  File "F:\Downloads\blender-3.1.2\3.1\python\lib\json\encoder.py", line 325, in _iterencode_list
    yield from chunks
  File "F:\Downloads\blender-3.1.2\3.1\python\lib\json\encoder.py", line 405, in _iterencode_dict
    yield from chunks
  File "F:\Downloads\blender-3.1.2\3.1\python\lib\json\encoder.py", line 405, in _iterencode_dict
    yield from chunks
  File "F:\Downloads\blender-3.1.2\3.1\python\lib\json\encoder.py", line 405, in _iterencode_dict
    yield from chunks
  File "F:\Downloads\blender-3.1.2\3.1\python\lib\json\encoder.py", line 438, in _iterencode
    o = _default(o)
  File "F:\Downloads\blender-3.1.2\3.1\scripts\addons\io_scene_gltf2\blender\com\gltf2_blender_json.py", line 28, in default
    return super(BlenderJSONEncoder, self).default(obj)
  File "F:\Downloads\blender-3.1.2\3.1\python\lib\json\encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type bpy_prop_array is not JSON serializable

location: <unknown location>:-1

**Comment by ronh991** [comment]
The SSS material is currently not supported,  Don't know if ASOBO will change that in the future.

**Comment by Michael-Cependa** [comment]
Thanks for looking into this.  I have some buttons in the L1011 I am
modelling that are translucent. They would look formidable if subsurface
scattering would work, but I can make do if it doesn't.

**Comment by y-khodja** [comment]
Hello, 

You can now update your add-on and get the Release 1.1.7, the SSS export is fixed . 

Thank you !
