### ISSUE TITLE
Multiple errors in export after edit (model previously working) - Removing edits, didn't work

### ISSUE THREAD

**Issue by Losco-Nosciuto** [AsoboStudio/glTF-Blender-IO-MSFS#192]
### Current Behavior

When exporting, a previously working project fails to export. No matter if I try to export only the LOD I edited, another one I did not edit, or all of them. The error is consistent among all tries. This is the first time after a few weeks not exporting the model, which previously was exported correctly

```
Error: Python: Traceback (most recent call last):
  File "C:\Users\Chris Da Ros\AppData\Roaming\Blender Foundation\Blender\3.1\scripts\addons\io_scene_gltf2_msfs\io\msfs_multi_export.py", line 171, in execute
    MSFS_OT_MultiExportGLTF2.export(
  File "C:\Users\Chris Da Ros\AppData\Roaming\Blender Foundation\Blender\3.1\scripts\addons\io_scene_gltf2_msfs\io\msfs_multi_export.py", line 45, in export
    bpy.ops.export_scene.gltf(
  File "C:\Program Files\Blender Foundation\Blender 3.1\3.1\scripts\modules\bpy\ops.py", line 132, in __call__
    ret = _op_call(self.idname_py(), None, kw)
RuntimeError: Error: Python: Traceback (most recent call last):
  File "C:\Program Files\Blender Foundation\Blender 3.1\3.1\scripts\addons\io_scene_gltf2\__init__.py", line 651, in execute
    return gltf2_blender_export.save(context, export_settings)
  File "C:\Program Files\Blender Foundation\Blender 3.1\3.1\scripts\addons\io_scene_gltf2\blender\exp\gltf2_blender_export.py", line 46, in save
    json, buffer = __export(export_settings)
  File "C:\Program Files\Blender Foundation\Blender 3.1\3.1\scripts\addons\io_scene_gltf2\blender\exp\gltf2_blender_export.py", line 71, in __export
    json = __fix_json(exporter.glTF.to_dict())
  File "C:\Program Files\Blender Foundation\Blender 3.1\3.1\scripts\addons\io_scene_gltf2\io\com\gltf2_io.py", line 1203, in to_dict
    result["materials"] = from_union([lambda x: from_list(lambda x: to_class(Material, x), x), from_none],
  File "C:\Program Files\Blender Foundation\Blender 3.1\3.1\scripts\addons\io_scene_gltf2\io\com\gltf2_io.py", line 56, in from_union
    assert False
AssertionError

location: C:\Program Files\Blender Foundation\Blender 3.1\3.1\scripts\modules\bpy\ops.py:132



location: <unknown location>:-1
```

### Expected Behavior

Should be exporting correctly, AT LEAST LOD03 when trying to export that alone, which has not been edited

### Steps To Reproduce

Load .blend file
try to export

### Environment

```markdown
- OS: Windows 11
- Blender: 3.1.2
- glTF-Blender-IO-MSFS: 1.1.6
```

### Anything else?

[Casetta.zip](https://github.com/AsoboStudio/glTF-Blender-IO-MSFS/files/10448666/Casetta.zip)

**Comment by Losco-Nosciuto** [comment]
Update 1 - been spending all night working on it and made a few tests.

- removed all materials and references, all images and tried to export. Same error

- tried exporting all LODs one by one hoping to find a faulty one. No luck. All of them are giving errors.
- copied and pasted the project in a new .Blend file. Same error.
- tried removing all items used from my Assets Library (appended). Still error.
- Tried all the above at once. No materials, no images, no LOD00, 01 and 02, keeping only LOD03. Same error occurs

**Comment by btronquo** [comment]
Hi @Losco-Nosciuto , 
FYI, the textures are not packed in your blender file
Did you try with blender 3.2 ? I did it and the export is OK
Is this bellow installed and activated in your blender settings :
![image](https://user-images.githubusercontent.com/5455001/213403104-13028883-ad9f-4ec8-acfd-d1eeb950ad79.png)

**Comment by Losco-Nosciuto** [comment]
> Hi @Losco-Nosciuto , FYI, the textures are not packed in your blender file Did you try with blender 3.2 ? I did it and the export is OK Is this bellow installed and activated in your blender settings : ![image](https://user-images.githubusercontent.com/5455001/213403104-13028883-ad9f-4ec8-acfd-d1eeb950ad79.png)



Hi Boris! No I haven't tried with Blender 3.2 as for now the most stable and reliable version working with the explorer seems to be 3.1.2.

Texture aren't packed due to size. 150MB don't fit in here, also yes. The gltf plugin included with blender is installed and active. I tried removing everything from the .blend file and add a cube only, and it exports, just won't export with something which is in here and that seems to affect all the rest for some weird reason

**Comment by Losco-Nosciuto** [comment]
![image](https://user-images.githubusercontent.com/35420766/213467016-4d20713f-392b-4ef4-b15a-d073ac429aa7.png)


Here's the thing, which has been already reported.
Exporting with 3.2 fixes the exporting error but prevent the model from being compiled into the sim due to the KHR_Punctual_Lights glTF extension. Any plausible workaround in this inside 1.1.6 with Blender 3.2?

**Comment by y-khodja** [comment]
Hello, 

I just pushed the fix for the "KHR_Lights_punctual" problem here: 
https://github.com/AsoboStudio/glTF-Blender-IO-MSFS/pull/194

Thank your for your reports !

**Comment by y-khodja** [comment]
In the future we recommend to use the Blender 3.3 LTS versions to avoid problems with the blender exporter.

**Comment by Losco-Nosciuto** [comment]
![image](https://user-images.githubusercontent.com/35420766/213756023-261b3ecb-7acb-4e34-bb14-625b45afb4f3.png)


Traceback (most recent call last):
  File "C:\Users\Chris Da Ros\AppData\Roaming\Blender Foundation\Blender\3.3\scripts\addons\io_scene_gltf2_msfs\io\msfs_multi_export.py", line 171, in execute
    MSFS_OT_MultiExportGLTF2.export(
  File "C:\Users\Chris Da Ros\AppData\Roaming\Blender Foundation\Blender\3.3\scripts\addons\io_scene_gltf2_msfs\io\msfs_multi_export.py", line 45, in export
    bpy.ops.export_scene.gltf(
  File "C:\Program Files\Blender Foundation\Blender 3.3\3.3\scripts\modules\bpy\ops.py", line 113, in __call__
    ret = _op_call(self.idname_py(), None, kw)
TypeError: Converting py args to operator properties: : keyword "export_displacement" unrecognized
Error: Python: Traceback (most recent call last):
  File "C:\Users\Chris Da Ros\AppData\Roaming\Blender Foundation\Blender\3.3\scripts\addons\io_scene_gltf2_msfs\io\msfs_multi_export.py", line 171, in execute
    MSFS_OT_MultiExportGLTF2.export(
  File "C:\Users\Chris Da Ros\AppData\Roaming\Blender Foundation\Blender\3.3\scripts\addons\io_scene_gltf2_msfs\io\msfs_multi_export.py", line 45, in export
    bpy.ops.export_scene.gltf(
  File "C:\Program Files\Blender Foundation\Blender 3.3\3.3\scripts\modules\bpy\ops.py", line 113, in __call__
    ret = _op_call(self.idname_py(), None, kw)
TypeError: Converting py args to operator properties: : keyword "export_displacement" unrecognized


Now this ;) @y-khodja

**Comment by Losco-Nosciuto** [comment]
![image](https://user-images.githubusercontent.com/35420766/213757646-047bc2a6-37fe-44f2-8fb5-d6c12876f6fe.png)
My bad, didn't update the plugin properly. Now I get this.


still, 3.3 LTS

`Error: Python: Traceback (most recent call last):
  File "C:\Users\Chris Da Ros\AppData\Roaming\Blender Foundation\Blender\3.3\scripts\addons\io_scene_gltf2_msfs\io\msfs_multi_export.py", line 207, in execute
    MSFS_OT_MultiExportGLTF2.export(
  File "C:\Users\Chris Da Ros\AppData\Roaming\Blender Foundation\Blender\3.3\scripts\addons\io_scene_gltf2_msfs\io\msfs_multi_export.py", line 82, in export
    bpy.ops.export_scene.gltf(
  File "C:\Program Files\Blender Foundation\Blender 3.3\3.3\scripts\modules\bpy\ops.py", line 113, in __call__
    ret = _op_call(self.idname_py(), None, kw)
RuntimeError: Error: Python: Traceback (most recent call last):
  File "C:\Program Files\Blender Foundation\Blender 3.3\3.3\scripts\addons\io_scene_gltf2\__init__.py", line 648, in execute
    return gltf2_blender_export.save(context, export_settings)
  File "C:\Program Files\Blender Foundation\Blender 3.3\3.3\scripts\addons\io_scene_gltf2\blender\exp\gltf2_blender_export.py", line 35, in save
    json, buffer = __export(export_settings)
  File "C:\Program Files\Blender Foundation\Blender 3.3\3.3\scripts\addons\io_scene_gltf2\blender\exp\gltf2_blender_export.py", line 60, in __export
    json = __fix_json(exporter.glTF.to_dict())
  File "C:\Program Files\Blender Foundation\Blender 3.3\3.3\scripts\addons\io_scene_gltf2\io\com\gltf2_io.py", line 1192, in to_dict
    result["materials"] = from_union([lambda x: from_list(lambda x: to_class(Material, x), x), from_none],
  File "C:\Program Files\Blender Foundation\Blender 3.3\3.3\scripts\addons\io_scene_gltf2\io\com\gltf2_io.py", line 45, in from_union
    assert False
AssertionError
Location: C:\Program Files\Blender Foundation\Blender 3.3\3.3\scripts\modules\bpy\ops.py:113`

**Comment by Losco-Nosciuto** [comment]
![image](https://user-images.githubusercontent.com/35420766/213791596-c94d2f82-1614-4e1e-b4ec-88b338111983.png)

```
Python: Traceback (most recent call last):
  File "C:\Users\Chris Da Ros\AppData\Roaming\Blender Foundation\Blender\3.3\scripts\addons\io_scene_gltf2_msfs\io\msfs_multi_export.py", line 207, in execute
    MSFS_OT_MultiExportGLTF2.export(
  File "C:\Users\Chris Da Ros\AppData\Roaming\Blender Foundation\Blender\3.3\scripts\addons\io_scene_gltf2_msfs\io\msfs_multi_export.py", line 82, in export
    bpy.ops.export_scene.gltf(
  File "C:\Program Files\Blender Foundation\Blender 3.3\3.3\scripts\modules\bpy\ops.py", line 113, in __call__
    ret = _op_call(self.idname_py(), None, kw)
RuntimeError: Error: Python: Traceback (most recent call last):
  File "C:\Program Files\Blender Foundation\Blender 3.3\3.3\scripts\addons\io_scene_gltf2\__init__.py", line 648, in execute
    return gltf2_blender_export.save(context, export_settings)
  File "C:\Program Files\Blender Foundation\Blender 3.3\3.3\scripts\addons\io_scene_gltf2\blender\exp\gltf2_blender_export.py", line 35, in save
    json, buffer = __export(export_settings)
  File "C:\Program Files\Blender Foundation\Blender 3.3\3.3\scripts\addons\io_scene_gltf2\blender\exp\gltf2_blender_export.py", line 60, in __export
    json = __fix_json(exporter.glTF.to_dict())
  File "C:\Program Files\Blender Foundation\Blender 3.3\3.3\scripts\addons\io_scene_gltf2\io\com\gltf2_io.py", line 1192, in to_dict
    result["materials"] = from_union([lambda x: from_list(lambda x: to_class(Material, x), x), from_none],
  File "C:\Program Files\Blender Foundation\Blender 3.3\3.3\scripts\addons\io_scene_gltf2\io\com\gltf2_io.py", line 45, in from_union
    assert False
AssertionError
Location: C:\Program Files\Blender Foundation\Blender 3.3\3.3\scripts\modules\bpy\ops.py:113
```


@y-khodja 
Tried again from "scratch"

re-exported the original model to a new blender file (Original model without LODs is inside a global blender file, then I create single blender files per model to export. I remade the exporting blender file for this cabin.)

re-exported the textures from Adobe Painter

Re-Created materials from scratch 

Tried to export with the issue above. Hope a solution is incoming soon.

**Comment by ronh991** [comment]
I've downloaded your blend file and can export the LODs using the multi export - I have to change the folder names, but that should not be the issue.

Are you downloading the release 1.1.6 - or are you downloading the "main" branch.  Please use the "main" branch as it has all the recent updates, including functionality with Blender 3.3

next try deleting the 

C:\Users\Chris Da Ros\AppData\Roaming\Blender Foundation\Blender\3.3\scripts\addons\io_scene_gltf2_msfs

folder.  Do you know how to install via the install menu in the edit preferences menu using a zip file? 

with that you must create a zip of the program in the addons/io_scene_glts2_msfs folder.

![DA40CGDFQ_2023 01 20_15h41m17s_08](https://user-images.githubusercontent.com/19254353/213801561-5d7e9a25-33c3-4dc4-aa8c-8d4249477632.png)

![DA40CGDFQ_2023 01 20_15h43m16s_09](https://user-images.githubusercontent.com/19254353/213801746-05fdc6a8-cc67-427e-a71a-f9f7821c4a9e.png)

**Comment by Losco-Nosciuto** [comment]
> I've downloaded your blend file and can export the LODs using the multi export - I have to change the folder names, but that should not be the issue.
> 
> Are you downloading the release 1.1.6 - or are you downloading the "main" branch. Please use the "main" branch as it has all the recent updates, including functionality with Blender 3.3
> 
> next try deleting the
> 
> C:\Users\Chris Da Ros\AppData\Roaming\Blender Foundation\Blender\3.3\scripts\addons\io_scene_gltf2_msfs
> 
> folder. Do you know how to install via the install menu in the edit preferences menu using a zip file?
> 
> with that you must create a zip of the program in the addons/io_scene_glts2_msfs folder.
> 
> ![DA40CGDFQ_2023 01 20_15h41m17s_08](https://user-images.githubusercontent.com/19254353/213801561-5d7e9a25-33c3-4dc4-aa8c-8d4249477632.png)
> 
> ![DA40CGDFQ_2023 01 20_15h43m16s_09](https://user-images.githubusercontent.com/19254353/213801746-05fdc6a8-cc67-427e-a71a-f9f7821c4a9e.png)

What you mean with change the folder names?

Apart from that yeah, I totally removed the old exporter and installed the new one from the main branch when I saw patches have been made without an actual release.

Those are the errors I'm getting no matter of the process. Unfortunately I'm not into python so can't help in reading what the error is about but I've been doing exactly as you suggested. And that's the error I've incurred into. Could this be because of appended assets from my personal assets library? If ever tho even removing those doesn't change the outcome. 
I'm really finding an hard time understanding what's going on. That error appears both on 3.1.2 and 3.3 LTS with the main branch addon installed manually

**Comment by ronh991** [comment]
I'm saying delete the version you have in the 
C:\Users\Chris Da Ros\AppData\Roaming\Blender Foundation\Blender\3.3\scripts\addons\io_scene_gltf2_msfs
folder.

Then install a zip file of the downloaded "main" branch on git - but zip up the 
glTF-Blender-IO-MSFS\addons\io_scene_gltf2_msfs
folder as shown in the picture above.  The release version 1.1.6 does not have the fixes you may need.

I also downloaded your blend file and it works on my system.. I can only conclude there is something wrong in your setup causing this error.

Please tell us step by step what you did so we can try to reproduce this error.

![DA40CGDFQ_2023 01 21_10h08m50s_14](https://user-images.githubusercontent.com/19254353/213873186-46875215-c07a-418b-9fa8-5d9d2b78b40b.png)

**Comment by Losco-Nosciuto** [comment]
Addon is installed properly as I said above. 
I installed 3.3LTS, downloaded the main branch from here, extracted the io_scene_gltf2_msfs to my 3.3 addon folder in AppData\Roaming\Blender Foundation\Blender\3.3\scripts\addons, then enabled it in Blender via Preferences / Add-Ons

What's weird is that, the error is consistent along 3.1.2 across to 3.3LTS.

So, might be something inside my blend file? That's why I asked if **appended assets from the Asset Library** work correctly or those might be the cause. Maybe messing something in the blend file which can't be still fixed after removing them?


Now gonna try to delete and clean Install Blender and see if that works. Gonna send a Loom video with the AddOn Installation process and exporter behviour if this doesn't fix it

**Comment by Losco-Nosciuto** [comment]
So, seems like cleaning all Blender Files and installing 3.3 LTS from scratch fixed the issue.
Still can't figure out what has been going on, probably there are a few Blender files shared across versions.
3.3 Was freshly installed already at first try, but didn't help. 

had to manually clean up registry keys, folders and all the user data in order to have it working back again!

Thanks for your help @ronh991 @y-khodja !
