### ISSUE TITLE
Cannot enable the Addon

### ISSUE THREAD

**Issue by djmanic** [AsoboStudio/glTF-Blender-IO-MSFS#293]
### Current Behavior

Here is the error I'm getting:

Traceback (most recent call last):
  File "C:\Program Files\Blender Foundation\Blender 4.0\4.0\scripts\modules\addon_utils.py", line 364, in enable
    mod = importlib.import_module(module_name)
  File "C:\Program Files\Blender Foundation\Blender 4.0\4.0\python\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "C:\Program Files\Blender Foundation\Blender 4.0\4.0\scripts\addons\io_scene_gltf2_msfs\__init__.py", line 216, in <module>
    from .io.msfs_import import Import
  File "C:\Program Files\Blender Foundation\Blender 4.0\4.0\scripts\addons\io_scene_gltf2_msfs\io\msfs_import.py", line 18, in <module>
    from .msfs_material import MSFSMaterial
  File "C:\Program Files\Blender Foundation\Blender 4.0\4.0\scripts\addons\io_scene_gltf2_msfs\io\msfs_material.py", line 16, in <module>
    from io_scene_gltf2.blender.exp.gltf2_blender_gather_texture_info import (
ModuleNotFoundError: No module named 'io_scene_gltf2.blender.exp.gltf2_blender_gather_texture_info'

### Expected Behavior

Enable 

### Steps To Reproduce

Go into preferences and addon 

### Environment

```markdown
- OS:Win10
- Blender:4.0
- glTF-Blender-IO-MSFS:1.3.2
```

**Comment by ronh991** [comment]
Does not work in Version 4.0 - please read the readme file

**Comment by djmanic** [comment]
> Does not work in Version 4.0 - please read the readme file. Only ver 3.3
> 
> https://www.blender.org/download/lts/3-3/

Thank you!
