### ISSUE TITLE
Error when trying to export

### ISSUE THREAD

**Issue by IamHappyDei** [AsoboStudio/glTF-Blender-IO-MSFS#333]
### Current Behavior

When I try to export an object it gives me this error:

Python: Traceback (most recent call last):
  File "C:\Users\Dei5k\AppData\Roaming\Blender Foundation\Blender\4.2\scripts\addons\io_scene_gltf2_msfs\io\msfs_multi_export.py", line 298, in execute
    MSFS_OT_MultiExportGLTF2.export(exportPath)
  File "C:\Users\Dei5k\AppData\Roaming\Blender Foundation\Blender\4.2\scripts\addons\io_scene_gltf2_msfs\io\msfs_multi_export.py", line 208, in export
    gltf = export_blender_3_6(file_path, settings)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Dei5k\AppData\Roaming\Blender Foundation\Blender\4.2\scripts\addons\io_scene_gltf2_msfs\io\msfs_multi_export.py", line 121, in export_blender_3_6
    return bpy.ops.export_scene.gltf(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\Blender Foundation\Blender 4.2\4.2\scripts\modules\bpy\ops.py", line 109, in __call__
    ret = _op_call(self.idname_py(), kw)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: Converting py args to operator properties:: keyword "export_colors" unrecognized

### Expected Behavior

to export the mesh

### Steps To Reproduce

-

### Environment

```markdown
- OS: Windows 11
- Blender: Blender: 4.2 LTS
- glTF-Blender-IO-MSFS:Last Version
```

**Comment by Pyscen312** [comment]
Wrong Blender version used for this exporter.   Either 3.3.x or 3.6.x. should be used for this exporter per the Readme file.
