### ISSUE TITLE
Setting base color texture cause error

### ISSUE THREAD

**Issue by ronh991** [AsoboStudio/glTF-Blender-IO-MSFS#77]
### Current Behavior

Setting a texture to Base Color causes error. - not shown

### Expected Behavior

to add texture to texture node

### Steps To Reproduce

Open model
migrate standard texture (has standard texture already) will not carry over.
set the texture to the required texture get error.

Traceback (most recent call last):
  File "C:\Users\Ron\AppData\Roaming\Blender Foundation\Blender\3.1\scripts\addons\io_scene_gltf2_msfs\blender\msfs_material_prop_update.py", line 128, in update_base_color_texture
    msfs.setBaseColorTex(self.msfs_base_color_texture)
AttributeError: 'NoneType' object has no attribute 'setBaseColorTex'
File "C:\Users\Ron\AppData\Roaming\Blender Foundation\Blender\3.1\scripts\addons\io_scene_gltf2_msfs\blender\msfs_material_prop_update.py", line 123, in update_base_color_texture
Traceback (most recent call last):
  File "C:\Users\Ron\AppData\Roaming\Blender Foundation\Blender\3.1\scripts\addons\io_scene_gltf2_msfs\blender\msfs_material_prop_update.py", line 128, in update_base_color_texture
    msfs.setBaseColorTex(self.msfs_base_color_texture)
AttributeError: 'NoneType' object has no attribute 'setBaseColorTex'
File "C:\Users\Ron\AppData\Roaming\Blender Foundation\Blender\3.1\scripts\addons\io_scene_gltf2_msfs\blender\msfs_material_prop_update.py", line 123, in update_base_color_texture

### Environment

```markdown
- OS:win 10
- Blender:3.1
- glTF-Blender-IO-MSFS:1.1.2
```

**Comment by ronh991** [comment]
![DA40CGDFQ_March 18, 2022_14h51m38s](https://user-images.githubusercontent.com/19254353/159066170-2346a97b-d57e-420e-b804-5850840e4a6d.png)

**Comment by mamu82** [comment]
Here migrate material works fine

That .001 in the texture name Is suspicious, Is your texture name really that?
Usually a .001 come from copying textured meshes between files, and cause missing textures in the Sim

Just my 2 cents 😊

**Comment by BlueMeshs** [comment]
Delete your actual material and create a new one, it should work correctly. It happen when you copy a mesh from an other .blend file.

**Comment by pepperoni505** [comment]
@ronh991 Does the above solve your issue?

**Comment by ronh991** [comment]
Guys this is due to the migration of materials.  The 001 was me doing things numerous times. trying to add the material manually after the migration.

This is the error with migrate.

**Comment by ronh991** [comment]
this is the error after trying to add the texture myself

location: <unknown location>:-1


Traceback (most recent call last):
  File "C:\Users\Ron\AppData\Roaming\Blender Foundation\Blender\3.1\scripts\addons\io_scene_gltf2_msfs\blender\msfs_material_prop_update.py", line 128, in update_base_color_texture
    msfs.setBaseColorTex(self.msfs_base_color_texture)
AttributeError: 'NoneType' object has no attribute 'setBaseColorTex'
File "C:\Users\Ron\AppData\Roaming\Blender Foundation\Blender\3.1\scripts\addons\io_scene_gltf2_msfs\blender\msfs_material_prop_update.py", line 123, in update_base_color_texture
Traceback (most recent call last):
  File "C:\Users\Ron\AppData\Roaming\Blender Foundation\Blender\3.1\scripts\addons\io_scene_gltf2_msfs\blender\msfs_material_prop_update.py", line 128, in update_base_color_texture
    msfs.setBaseColorTex(self.msfs_base_color_texture)
AttributeError: 'NoneType' object has no attribute 'setBaseColorTex'
File "C:\Users\Ron\AppData\Roaming\Blender Foundation\Blender\3.1\scripts\addons\io_scene_gltf2_msfs\blender\msfs_material_prop_update.py", line 123, in update_base_color_texture

**Comment by ronh991** [comment]
fixed in migration fix branch
